-- AlterTable
ALTER TABLE `productos` ADD COLUMN `destacado` VARCHAR(191) NOT NULL DEFAULT 'N',
    ADD COLUMN `oferta` VARCHAR(191) NOT NULL DEFAULT 'N',
    ADD COLUMN `stock` INTEGER NOT NULL DEFAULT 200;
